# Generated by Django 3.1.3 on 2020-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201115_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default-avatar.jpg', upload_to='avatars'),
        ),
    ]
