# Generated by Django 3.1.3 on 2020-11-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_city'),
        ('users', '0005_auto_20201115_1733'),
    ]

    operations = [
    ]
