# Generated by Django 3.1.3 on 2020-11-13 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('szafy', 'szafy'), ('komody', 'komody'), ('sofy', 'sofy'), ('zestawy wypoczynkowe', 'zestawy wypoczynkowe'), ('meblościanki', 'meblościanki'), ('ławy i stoliki', 'ławy i stoliki'), ('krzesła', 'krzesła')], max_length=100, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data opublikowania'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='picture',
            field=models.ImageField(upload_to='annouc_photos', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sell_or_exchange',
            field=models.CharField(choices=[('na sprzedaż', 'na sprzedaż'), ('na wymianę', 'na wymianę'), ('na sprzedaż lub wymianę', 'na sprzedaż lub wymianę')], max_length=100, verbose_name='Wymiana/Sprzedaż'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='shipping',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=100, verbose_name='Wysyłka'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tytuł'),
        ),
    ]
