# Generated by Django 3.1.3 on 2020-11-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20201113_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='czy ogłoszenie jest promowane?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='picture',
            field=models.ImageField(upload_to='announc_photos', verbose_name='Zdjęcie'),
        ),
    ]
