# Generated by Django 3.1.3 on 2020-11-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20201121_1910'),
        ('announcements', '0003_auto_20201115_2206'),
    ]

    operations = [
    ]
