# Generated by Django 3.1.3 on 2020-11-22 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_merge_20201122_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='announcements.category'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='czy ogłoszenie jest promowane?'),
        ),
    ]
